### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined on latest 6.2.2 client

### ISSUE THREAD

**Issue by sreplans** [SocketCluster/asyngular#11]
first fo all, thanks for this great library :)

After updating to the latest asyngular , I now get  this error when starting the server.js:
ReferenceError: regeneratorRuntime is not defined
    at /root/asyg/test/node_modules/asyngular-client/asyngular-client.min.js:4:70849
    at /root/asyg/test/node_modules/asyngular-client/asyngular-client.min.js:4:71176
    at Object.12 (/root/asyg/test/node_modules/asyngular-client/asyngular-client.min.js:4:71933)
    at o (/root/asyg/test/node_modules/asyngular-client/asyngular-client.min.js:4:3629)
    at /root/asyg/test/node_modules/asyngular-client/asyngular-client.min.js:4:3663
    at Object.31../consumer (/root/asyg/test/node_modules/asyngular-client/asyngular-client.min.js:4:101292)
    at o (/root/asyg/test/node_modules/asyngular-client/asyngular-client.min.js:4:3629)
    at /root/asyg/test/node_modules/asyngular-client/asyngular-client.min.js:4:3663
    at Object.24../demuxed-consumable-stream (/root/asyg/test/node_modules/asyngular-client/asyngular-client.min.js:4:92913)
    at o (/root/asyg/test/node_modules/asyngular-client/asyngular-client.min.js:4:3629)

I was able to replicate this on a clean machine that never had asyngular:

root@Debian-94-stretch-64-minimal ~ # npm install -g asyngular
/usr/bin/asyngular -> /usr/lib/node_modules/asyngular/bin/cli.js
+ asyngular@6.1.1
added 55 packages from 37 contributors in 5.888s
root@Debian-94-stretch-64-minimal ~ # mkdir asyg
root@Debian-94-stretch-64-minimal ~ # cd asyg/
root@Debian-94-stretch-64-minimal ~/asyg # asyngular create test
Creating app structure...
Installing app dependencies using npm. This could take a while...

> nodemon@1.19.4 postinstall /root/asyg/test/node_modules/nodemon
> node bin/postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ws@7.2.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN asyngular-sample@1.0.0 No repository field.
npm WARN asyngular-sample@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 310 packages from 182 contributors and audited 2560 packages in 8.715s
found 0 vulnerabilities

[Success] Asyngular app "/root/asyg/test" was setup successfully.
root@Debian-94-stretch-64-minimal ~/asyg # cd test/
root@Debian-94-stretch-64-minimal ~/asyg/test # ls
Dockerfile  kubernetes  node_modules  nodemon.json  package.json  package-lock.json  public  server.js
root@Debian-94-stretch-64-minimal ~/asyg/test # node server.js
/root/asyg/test/node_modules/asyngular-client/asyngular-client.min.js:4
 "use strict";function _classCallCheck(t,e){if(!(t instanceof e))throw new TypeError("Cannot call a class as a function")}function _defineProperties(t,e){for(var n=0;n<e.length;n++){var r=e[n];r.enumerable=r.enumerable||!1,r.configurable=!0,"value"in r&&(r.writable=!0),Object.defineProperty(t,r.key,r)}}function _createClass(t,e,n){return e&&_defineProperties(t.prototype,e),n&&_defineProperties(t,n),t}function _possibleConstructorReturn(t,e){return!e||"object"!==_typeof(e)&&"function"!=typeof e?_assertThisInitialized(t):e}function _assertThisInitialized(t){if(void 0===t)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return t}function _getPrototypeOf(t){return(_getPrototypeOf=Object.setPrototypeOf?Object.getPrototypeOf:function(t){return t.__proto__||Object.getPrototypeOf(t)})(t)}function _inherits(t,e){if("function"!=typeof e&&null!==e)throw new TypeError("Super expression must either be null or a f

**ReferenceError: regeneratorRuntime is not defined**
    at /root/asyg/test/node_modules/asyngular-client/asyngular-client.min.js:4:70849
    at /root/asyg/test/node_modules/asyngular-client/asyngular-client.min.js:4:71176
    at Object.12 (/root/asyg/test/node_modules/asyngular-client/asyngular-client.min.js:4:71933)
    at o (/root/asyg/test/node_modules/asyngular-client/asyngular-client.min.js:4:3629)
    at /root/asyg/test/node_modules/asyngular-client/asyngular-client.min.js:4:3663
    at Object.31../consumer (/root/asyg/test/node_modules/asyngular-client/asyngular-client.min.js:4:101292)
    at o (/root/asyg/test/node_modules/asyngular-client/asyngular-client.min.js:4:3629)
    at /root/asyg/test/node_modules/asyngular-client/asyngular-client.min.js:4:3663
    at Object.24../demuxed-consumable-stream (/root/asyg/test/node_modules/asyngular-client/asyngular-client.min.js:4:92913)
    at o (/root/asyg/test/node_modules/asyngular-client/asyngular-client.min.js:4:3629)
root@Debian-94-stretch-64-minimal ~/asyg/test #

**Comment by jondubois** [comment]
Thanks. This was fixed in asyngular-client. https://github.com/SocketCluster/asyngular-client/commit/a5e0d62f7c628f45b5c4a75c144895d93da53590
