### ISSUE TITLE
Asyngular vs. SocketCluster

### ISSUE THREAD

**Issue by mkhahani** [SocketCluster/asyngular#2]
What is the purpose of Asyngular? Which one should I pick as a framework?

**Comment by jondubois** [comment]
@mkhahani It's like SocketCluster but it works better with async/await. For a lot of use cases, it should help you to write cleaner code with fewer bugs but it requires a strong understanding of async/await (and the new `for-await-of` loop). It's ideal if you want to have complete control over the flow and order of messages as they traverse your system and also third party APIs/services.

Also, Asyngular is designed to work nicely with new ECMAScript features such as async generators. For example, you could pass an Asyngular stream as an argument to an async generator and generate a filtered substream that you can iterate over independently.

It should enable some interesting use cases which would have been much too complex to implement in SC.

**Comment by mkhahani** [comment]
That's great! So no more updates on the legacy project, right? Maybe just bug fixes?
By the way SocketCluster is nicer than Asyngular as the project name :)

**Comment by jondubois** [comment]
@mkhahani SC is not going to be a legacy project. It will still receive bug fixes and minor updates but probably no major new features.

**Comment by mkhahani** [comment]
Thanks for the clarification. I'm planning to start my project based on Asyngular soon.

**Comment by mkhahani** [comment]
Sorry for reopening the issue.
I see no worker/broker in the sample app nor in the docs. Does Asyngular supports native scaling(SCC) without using Kubernetes?

**Comment by mkhahani** [comment]
I found it :)
https://github.com/SocketCluster/asyngular/blob/master/agc-guide.md

**Comment by bkniffler** [comment]
Just wanted to chime in, been testing Asyngular and I totally love the async/await focused flow! Using it feels super natural, can't wait to push it to the limits :)

**Comment by elieobeid7** [comment]
Seems to me that the team killed socketcluster and the new project didn't pick up steam so it killed two projects at once. I'm afraid to use this project simply because too few users are using it.

Also the name is super bad, if you're trying to google tutorials, you get Angular tutorials instead, learning this project is going to be a challenge because of the name and because of its popularity.

**Comment by jondubois** [comment]
@elieobeid7 Thanks for this honest feedback.

SocketCluster is still very much alive and commits are still being made to it but this is a very good point and you're not the first to mention about the name "Asyngular". I've raised a new issue to help decide how to move forward so feel free to write a short proposal or give additional feedback: https://github.com/SocketCluster/asyngular/issues/4

There is still a lot of flexibility regarding how to move forward. The fact that it hasn't gained too much traction at this stage is also a good thing ;)
