### ISSUE TITLE
Use in node 8

### ISSUE THREAD

**Issue by bkniffler** [SocketCluster/asyngular#6]
AWS Lambda only supports node 8, is there any way to make it work for older versions? async/await is not supported there.

**Comment by jondubois** [comment]
@bkniffler you could try running asyngular-server through babel to transpile it to node 8. It relies a lot on async/await internally.

**Comment by bkniffler** [comment]
Hey, I've worked this out, thanks! After trying different things, this solution worked best:

```
import 'core-js/modules/es7.symbol.async-iterator';
```

Just insert before importing asyngular.
